### ISSUE TITLE
render後，區塊二會跑版

### ISSUE THREAD

**Issue by winnie145ch** [a5757657/f2e-responsive-web-design#21]
目前試著用 usestate 但會報錯 `Uncaught TypeError: setPos is not a function` 
待解決

https://user-images.githubusercontent.com/96521576/201509853-27883c8c-16ca-4b97-be5b-97566101c8fe.mp4

**Comment by a5757657** [comment]
是怎樣的問題 我在這個pr沒看到報錯
https://github.com/a5757657/f2e-responsive-web-design/pull/20

**Comment by winnie145ch** [comment]
在 FAQ 那邊我是用 useState render內容，
問題就發生在我按過按鈕 render 後，
section 2 就會產生 transform (如影片最後所示
我也是在確認上個pr才發現的

**Comment by a5757657** [comment]
第二區塊
視窗的高度試試看用resize去監聽，把高度存在state裡，mousemove在取用state存的視窗高度去計算移動的幅度

**Comment by winnie145ch** [comment]
感謝你的建議😭 只是我還沒寫出來，先直接調整移動幅度來處理
(盡力使用resize中
